xskillscore/__init__.py, xskillscore/core/deterministic.py, xskillscore/core/np_deterministic.py, xskillscore/tests/test_deterministic.py, xskillscore/tests/test_np_deterministic.py
no magic: based on your rmse implementation
=> added mse and mae

xskillscore/core/deterministic.py, xskillscore/tests/test_deterministic.py
I am still unsure whether this results in performance boost
=> change to dask parallelized

xskillscore/core/probabilistic.py, xskillscore/tests/test_probabilistic.py
https://github.com/raybellwaves/xskillscore/issues/13
- added two tests to check for if inputs are int
- if int, create xr.DataArray
=> bugfix for int float in prob

README.rst, ci/requirements-py36.yml, setup.py, xskillscore/__init__.py, xskillscore/core/probabilistic.py, xskillscore/tests/test_deterministic.py, xskillscore/tests/test_probabilistic.py
- Fixes https://github.com/raybellwaves/xskillscore/issues/19
- adds `properscoring.crps_quadrature`, `properscoring.brier_score`
- changes `test_env` to `xskillscore-dev` and add numba
=> make sure crps_ensemble can be probabilistic and pass through all args

.gitignore, asv_bench/asv.conf.json, asv_bench/benchmarks/__init__.py, asv_bench/benchmarks/deterministic.py, asv_bench/benchmarks/probabilistic.py, ci/requirements-py36.yml, xskillscore/core/probabilistic.py
- asv config json file
- benchmarks for probabilistic and deterministic
- `crps_quadrature` is skipped because takes too long
- benchmarks environments with or without bottleneck and numba
- why are the dasked benchmarks slower? (Changed setup to load to from file to make dask and non-dask more similar)
- do we need `np.rollaxis` in deterministic metrics? `xr.apply_ufunc` rolls back `core_dims` to the back anyways, see http://xarray.pydata.org/en/stable/computation.html: `With apply_ufunc, core dimensions are recognized by name, and then moved to the last dimension of any input arguments before applying the given function. This means that for functions that accept an axis argument, you usually need to set axis=-1.`
- there seems to be the possibility to push to gh-pages. do you use your …
=> introduce asv benchmark

xskillscore/core/deterministic.py, xskillscore/tests/test_deterministic.py
https://github.com/raybellwaves/xskillscore/issues/52
=> Handle array if integer

CHANGELOG.rst, asv_bench/asv.conf.json, asv_bench/benchmarks/xr_vs_xs.py, ci/run-linter.sh, xskillscore/core/deterministic.py, xskillscore/core/np_deterministic.py, xskillscore/tests/test_deterministic.py, xskillscore/tests/test_mask_skipna.py
closes https://github.com/raybellwaves/xskillscore/issues/64
Added:
- `_determine_input_core_dims`
- `_stack_input_if_needed`
- `xr_mse` and `xr_pearson_r` in `asv`
Creating errors right now:
- linting error: `(weights == None).all()`
=> weights perf

CHANGELOG.rst, xskillscore/core/np_deterministic.py, xskillscore/tests/test_skipna_functionality.py
Fix assignment read only destination
https://github.com/raybellwaves/xskillscore/issues/79
=> Fix assignment read only destination

.travis.yml, CHANGELOG.rst, HOWTOCONTRIBUTE.rst, ci/requirements-py36.yml
=> add coveralls

README.rst
=> add coveralls badge

README.rst
=> DOC: add binder badge

CHANGELOG.rst, setup.py
=> bump v0.0.16

HOWTOCONTRIBUTE.rst
=> DOC: add no deps to pip

xskillscore/core/deterministic.py, xskillscore/tests/test_deterministic.py, xskillscore/tests/test_skipna_functionality.py
Closes #165 #71? please check @hdrake #156 
-   [x]  Breaking change (fix or feature that would cause existing functionality to not work as expected)
-   [ ]  I have rebased onto master or develop (wherever I am merging) and dealt with any conflicts.
Please add any references to manuscripts, textbooks, etc.
=> broadcast dimensions not in dims

CHANGELOG.rst
=> fix CHANGELOG

.coveralls.yml, README.rst
Test that coveralls works now.
=> test coverage

xskillscore/core/probabilistic.py
- allows `brier_score` forecast with member, takes member mean
- docstring examples added
Closes #128 
is there a dostring examples tester? did manually...
-   [x]  I have added docstrings to all new functions.
-   [ ]  I have rebased onto master or develop (wherever I am merging) …
=> prob docstrings

README.rst, docs/source/index.rst
=> DOC: drop travis badge and update codecov

MANIFEST.in
This is one of these "should have" things that I learned about when adding packages on to conda-forge
=> add MANIFEST

.github/workflows/lint.yml, .github/workflows/xskillscore_installs.yml, .github/workflows/xskillscore_testing.yml
.
Closes #252 
-   [ ]  I have rebased onto master or …
=> Don’t expose secrets

CHANGELOG.rst, xskillscore/core/accessor.py, xskillscore/tests/test_accessor_probabilistic.py, xskillscore/tests/test_probabilistic.py
add ROC accessor
Closes #256 
-   [ ]  I have rebased onto …
=> add roc accessor

xskillscore/tests/test_metric_results_accurate.py, xskillscore/tests/test_weighted_metric_results_accurate.py
Related to #254 
-   [ ]  I have rebased onto master or …
=> add weight tests for np funcs

xskillscore/tests/test_probabilistic.py
just adding one more hard numbers example
I was hoping to find more test examples online but didnt.
=> add second wilks example

CHANGELOG.rst, xskillscore/core/comparative.py, xskillscore/core/np_deterministic.py, xskillscore/core/probabilistic.py, xskillscore/core/utils.py, xskillscore/tests/test_comparative.py, xskillscore/tests/test_deterministic.py, xskillscore/tests/test_probabilistic.py
Before: `========== 2558 passed, 4 skipped, 1901 warnings ==========`
Now: `=========== 2558 passed, 4 skipped, 83 warnings  ========`
reduce warnings:
Closes #41 
-   [ ]  I have …
=> reduce warnings

.github/workflows/xskillscore_testing.yml, CHANGELOG.rst, ci/dev.yml, setup.py
=> Drop py 36

CHANGELOG.rst, xskillscore/core/probabilistic.py
threshold coords was integer before. now take the values if given int or float
-   [ ] …
=> Update threshold coords in threshold brier score 

CHANGELOG.rst
=> release 0.0.19

HOWTORELEASE.rst
=> mention clone from source

.github/workflows/xskillscore_testing.yml, CHANGELOG.rst, ci/dev.yml, ci/doc.yml, ci/docs_notebooks.yml, ci/minimum-tests.yml
-   [ ]  I have rebased onto master or …
=> Speed up tests

.github/workflows/cancel-duplicate-runs.yaml, .github/workflows/upstream-dev-ci.yml, .github/workflows/xskillscore_installs.yml, .github/workflows/xskillscore_testing.yml, CHANGELOG.rst, README.rst, docs/source/index.rst, xskillscore/tests/test_resampling.py
- cancel duplicate actions
- Skip-ci
- Test-upstream
=>  [test-upstream] and [skip-ci]

.github/PULL_REQUEST_TEMPLATE.md, .github/workflows/upstream-dev-ci.yml, HOWTOCONTRIBUTE.rst, HOWTORELEASE.rst, README.rst, asv_bench/asv.conf.json, docs/source/index.rst
=> master to main fixes

CHANGELOG.rst, HOWTORELEASE.rst, requirements.txt
=> typos and update req

CHANGELOG.rst
=> new version in changelog

HOWTORELEASE.rst, xskillscore/core/deterministic.py
=> doc updates

.pre-commit-config.yaml, CHANGELOG.rst, ci/dev.yml, docs/source/contributors.rst, xskillscore/tests/test_mask_skipna.py, xskillscore/tests/test_probabilistic.py, xskillscore/tests/test_skipna_functionality.py
Add mypy to pre-commit to test type issues
Related to #317 
Mypy passes in pre-commit test
-   [x]  I have rebased onto main or develop (wherever I am merging) and dealt with any conflicts.
-   [x]  I have squashed commits to a reasonable amount, and force-pushed the squashed commits.
=> Add mypy to pre-commit-config and fix existing typing issues

xskillscore/tests/test_mask_skipna.py
PR #320 made me realize I forgot to use linslope in this file after importing
=> add linslope

CHANGELOG.rst, ci/dev.yml, ci/doc.yml, ci/docs_notebooks.yml, ci/minimum-tests.yml, requirements.txt
=> update xhistogram version

CHANGELOG.rst, xskillscore/core/resampling.py, xskillscore/tests/test_resampling.py
Closes #303 
-   [x]  Tests added for `pytest`, if necessary
=> dim in resample_idx not coords

CHANGELOG.rst
=> DOC: Update CHANGELOG.rst

CHANGELOG.rst, xskillscore/core/probabilistic.py, xskillscore/tests/test_probabilistic.py
broadcast
Closes #345
Closes https://github.com/pangeo-data/climpred/issues/653
=> `crps_ensemble` broadcasts

ci/doc.yml, requirements.txt
=> toolz needed?

ci/doc.yml
=> unpin `sphinx`

xskillscore/tests/test_deterministic.py
Closes #383 
~~fix for upstream while current version fails~~
~~merge once xarray is released~~
=> Fix upstream Error message

readthedocs.yml
=> `rtd` runs again

xskillscore/core/probabilistic.py
Closes #404 
-   [ ]  I have rebased onto main or develop …
=> Fix dask IndexError
