xarray-contrib/xskillscore

.gitignore, README.rst, xskillscore/core/deterministic.py, xskillscore/core/np_deterministic.py, xskillscore/tests/test_deterministic.py
I think it's ready
https://github.com/raybellwaves/xskillscore/issues/8
I think when you call xr.apply_ufunc, it automatically rolls the axes so I just had to pass in the right negative numbers to `axis` kwargs https://xarray.pydata.org/en/stable/generated/xarray.apply_ufunc.html
```
Core dimensions are automatically moved to the last axes of input variables before applying func, which facilitates using NumPy style generalized ufuncs [2].
```
A quick sanity check
```
import numpy as np
import xarray as xr
from xskillscore import mae
ds = xr.tutorial.open_dataset('air_temperature').isel(time=[0, 1, 2],
lat=[3, 4, 5],
lon=[6, 7, 8])
ds['ref'] = xr.concat((
ds['air'].isel(time=i) + i
for i in range(len(ds['time']))
), 'time')
print('test diagn\n\n')
mae(ds['air'], ds['ref'], ['time'])
for i …
```
=> Multi-dimensional support

README.rst, setup.py, xskillscore/__init__.py, xskillscore/core/accessor.py, xskillscore/tests/test_accessor.py
Give the users the option of doing: `ds.xs.rmse('air', 'airx2', 'time')` rather than `xs.rmse(ds['air'], ds['airx2'], 'time')`, although they can also do, `ds.xs.rmse('air', ds2['airx2'], 'time')` if `airx2` is not a variable in the original ds.
```
ds = xr.tutorial.open_dataset('air_temperature')
ds['airx2'] = ds['air']
xs.rmse(ds['air'], ds['airx2'], 'time')
ds.xs.rmse('air', 'airx2', 'time')
```
=> Add accessors

README.rst, xskillscore/core/deterministic.py, xskillscore/core/np_deterministic.py, xskillscore/core/probabilistic.py, xskillscore/tests/test_deterministic.py
Addresses https://github.com/raybellwaves/xskillscore/issues/27, https://github.com/raybellwaves/xskillscore/issues/16.
* Adds `weights` keyword to all deterministic functions
* Adds testing for `weights` for all deterministic functions
* Expands documentation and commenting
CC @brian-rose, @hdrake
=> Add optional weighting to `xskillscore` functions

README.rst, xskillscore/core/deterministic.py, xskillscore/core/np_deterministic.py, xskillscore/tests/test_deterministic.py, xskillscore/tests/test_mask_skipna.py
Addresses #30, #34, #35
This adds a `skipna=bool` option on all high-level deterministic functions. This is necessary in cases where the user enters in an `a` and `b` with say, a spatial mask applied (or with continents NaNed out even). Currently, the underlying numpy commands return NaNs since they encounter NaNs on the spatial grid while summing and taking means.
Here I just call a quick helper function which returns a variable function generically named, so it doesn't muddy up the code too much.
Testing just uses `['lat', 'lon']` and `['lat', 'lon', 'time']` since the NaN masking issue is very clear over these axes. Also `test_deterministic` assesses accuracy in the high level functions, weighting, etc. so I didn't want any redundancies here.
=> Add `skipna` option on high-level functions

xskillscore/core/np_deterministic.py, xskillscore/tests/test_deterministic.py, xskillscore/tests/test_mask_skipna.py, xskillscore/tests/test_np_deterministic.py
Since pearson_r works as expected, use the location of NaNs from pearson_r. Also less computation since it doesn't have to perform the mean.
https://github.com/raybellwaves/xskillscore/issues/45
=> Fix all nans in pearson_r pval

.travis.yml, ci/requirements-py36.yml, ci/run-linter.sh, setup.cfg, xskillscore/__init__.py, xskillscore/core/accessor.py, xskillscore/core/deterministic.py, xskillscore/core/np_deterministic.py, xskillscore/core/probabilistic.py, xskillscore/tests/test_accessor.py, xskillscore/tests/test_deterministic.py, xskillscore/tests/test_mask_skipna.py, xskillscore/tests/test_np_deterministic.py, xskillscore/tests/test_probabilistic.py
Addresses https://github.com/raybellwaves/xskillscore/issues/57. Blackens all code and tests, adds an auto-linter to the Travis CI (runs `flake8` and `black` as a PR check), and updates config files to have `flake8` comply with `black` standards.
=> Blacken code

CHANGELOG.rst, xskillscore/__init__.py, xskillscore/core/deterministic.py, xskillscore/core/np_deterministic.py, xskillscore/tests/test_deterministic.py, xskillscore/tests/test_gridded_metrics.py, xskillscore/tests/test_mask_skipna.py, xskillscore/tests/test_metric_results_accurate.py, xskillscore/tests/test_np_deterministic.py, xskillscore/tests/test_skipna_functionality.py
This PR fixes a bug with `skipna` where accurate results weren't reported if there were pairwise nans, e.g. nans that occurred in differing indices on `a` and `b`. I think this was only occurring with `pearson_r` and `spearman_r`.
The issue in these correlation ones was we would have `np.nanmean(a*b)` for instance, which dealt with nans in the same index. Then we would incorporate `np.nanmean(a*a)` which could bring in values that are actually nans in the `b` array. I hadn't thought of the pairwise issue since I usually work with model output that has nans in all the same places.
* Solves issue by creating nans at every pairwise location.
* Adds testing utilizing below case
* Adds testing for single time series for each metric compared to an outside package.
* Changed the name mad to …
=> Fix `skipna` bug

CHANGELOG.rst, xskillscore/__init__.py, xskillscore/core/deterministic.py, xskillscore/core/np_deterministic.py, xskillscore/tests/test_deterministic.py, xskillscore/tests/test_effective_p_value.py
This PR adds the "effective" p value for temporal autocorrelation, per section 5, equation 31 of Bretherton, Christopher S., et al. "The effective number of spatial degrees of freedom of a time-varying field." Journal of climate 12.7 (1999): 1990-2009. 
This is an important metric to include in geosciences where there tends to be a lot of temporal autocorrelation in time series, which artificially inflates correlation significance. 
This does not address spatial autocorrelation per e.g. Wilks, Daniels. "The stippling shows statistically significant grid points”: How research results are routinely overstated and overinterpreted, and what to do about it." Bulletin of the American Meteorological Society 97.12 (2016): 2263-2273. And I believe this is also addressed in the Bretherton paper. I …
=> Add effective p value

CHANGELOG.rst, xskillscore/core/np_deterministic.py
Fixes bug that returns error that arrays are read-only. Also avoids mutating the original arrays that were submitted when `skipna=True`.
Closes https://github.com/raybellwaves/xskillscore/issues/109
-   [X]  Bug fix (non-breaking change which fixes an issue)
I'm not sure how to test this yet. I've only replicated it in cases where `vectorize=True` on `xr.apply_ufunc`. So I'm not sure if @ahuang11 can replicate #109 so we can add it to testing. Regardless, this is a good addition to avoid mutating the original arrays `a` and `b` and it should also fix the read only bug.
-   [X]  I have commented my code, particularly in hard-to-understand areas
-   [X]  I have rebased onto master or develop …
=> fix read only bug

CHANGELOG.rst, xskillscore/core/accessor.py, xskillscore/core/probabilistic.py, xskillscore/tests/test_probabilistic.py
Closes #93 sounds reasonable @dougiesquire
-   [x]  Breaking change (fix or feature that would cause existing functionality to not work as expected)
-   [x]  I have added docstrings to all new functions.
-   [x]  I have commented my code, particularly in hard-to-understand areas
-   [x]  I have rebased onto master or develop (wherever I am merging) and dealt with any conflicts.
-   [ ]  I have squashed commits to a reasonable amount, and force-pushed the squashed …
=> probabilistic dim

xskillscore/core/accessor.py, xskillscore/tests/test_accessor_probabilistic.py
pass on all args and kwargs in accessors. then we cannot forget any kwargs. one step towards https://github.com/raybellwaves/xskillscore/issues/91
=> use args and kwargs in accessors

ci/requirements-py36.yml
Locks the version of `black` to `19.10b0` to deal with bug with `dataclasses` module in new release. We could force install of `dataclasses` in our dev environment, but `black` then also struggles with the string-normalization flag which deals with `"` vs. `'` and becomes a headache. We can switch back to the newest `black` releases once they address some of this.
=> lock black version

docs/source/conf.py
Use `xskillscore.__version__` to determine version for docs rendering.
Closes https://github.com/raybellwaves/xskillscore/issues/146
=> Automatically determine version in docs

ci/requirements-py36.yml, requirements.txt, xskillscore/core/deterministic.py
broke with xr0.16.1 where xr.0.16.0 was fine. problem was input_core_dims in xr.apply_ufunc.
fixed xr version to larger than xr0.16.1 in requirements and ci/env
Closes #183 
-   [ ]  I have rebased onto master or develop (wherever I am merging) and dealt with any conflicts.
Please add any references to manuscripts, textbooks, etc.
=> weights input_core_dims [] instead of [None]

CHANGELOG.rst
Release for version 0.0.18. Fixes incompatibilities with new `xarray=0.16.1`, introduces sign test, and speeds up `rmse`.
Closes https://github.com/raybellwaves/xskillscore/issues/185
=> Version 0.0.18 Release

.pre-commit-config.yaml, CHANGELOG.rst, HOWTOCONTRIBUTE.rst, README.rst, asv_bench/asv.conf.json, docs/source/conf.py, docs/source/contributors.rst, docs/source/index.rst, setup.py, xskillscore/core/np_deterministic.py, xskillscore/tests/test_skipna_functionality.py
Updates references from old `raybellwaves` repo to `xarray-contrib`. 
Forgot to install `pre-commit` on the new repo so might have some small errors from that.
=> change reference from raybellwaves to xarray-contrib

.github/workflows/lint.yml, .github/workflows/xskillscore_installs.yml, .github/workflows/xskillscore_testing.yml, .pre-commit-config.yaml, ci/dev.yml, ci/minimum-tests.yml, docs/source/api/xskillscore.Contingency.rst
Follows https://github.com/pangeo-data/climpred/pull/507.
* Uses `pre-commit` to lint. This ensures that the same linting environment is used on the dev side and in linting at the testing stage.
* Changes `pull_request_target` to `pull_request` so that updates to Github Actions are incorporated immediately on the PR.
* Updates `pre-commit` versions and releases version lock on `black`.
=> More GitHub actions updates

.github/workflows/xskillscore_testing.yml
Updates `setup-miniconda` to v2 in our CI. An upstream bug from Github Actions was introduced today that breaks it. See https://github.com/conda-incubator/setup-miniconda/issues/101.
=> Update `setup-miniconda` hook.

CHANGELOG.rst, ci/dev.yml, ci/docs_notebooks.yml, ci/minimum-tests.yml, requirements.txt, setup.py
https://github.com/xarray-contrib/xskillscore/issues/233
=> Fix py3.6 CI

CHANGELOG.rst, xskillscore/tests/conftest.py, xskillscore/tests/test_accessor_deterministic.py, xskillscore/tests/test_deterministic.py, xskillscore/tests/test_mask_skipna.py, xskillscore/tests/test_probabilistic.py, xskillscore/tests/test_skipna_functionality.py
Closes #246
Ignore the name of the branch. I worked on added nans to in the correlation tests.
I impact did a little bit of work on #245 but this doesn't close that.
I took out the `has_nan` parameter to the tests and instead moved to another test for nans which I could use `a_nan` from the conftest.py. Unfortunately it means duplicating most of the code in the test function but from reading some pytest docs they recommend using fixtures in the conftest.py as function imputs. Not sure if we create another function inside test_deterministic or even move some upstream to conftest.py to avoid the duplicated code.
=> add nan corr tests

xskillscore/core/np_deterministic.py, xskillscore/tests/test_weighted_metric_results_accurate.py
Closes #254 
-   [ ]  I have rebased onto master or …
=> add scipy weight tests

CHANGELOG.rst, xskillscore/tests/test_skipna_functionality.py
=> use raise_if_dask_computes from xarray

requirements.txt
=> Unpin dask

ci/dev.yml, ci/doc.yml, ci/docs_notebooks.yml, ci/minimum-tests.yml, requirements.txt
xhistogram=0.1.3 introduced an error that broke some functions in xskillscore (see https://github.com/xgcm/xhistogram/issues/48). This PR avoids this version of xhistogram.
Closes #288
-   [X]  Bug fix (non-breaking change which fixes an issue)
CI tests
-   [X]  I have commented my code, particularly in hard-to-understand areas
=> Avoid xhistogram=0.1.3

CHANGELOG.rst, xskillscore/core/probabilistic.py, xskillscore/tests/test_probabilistic.py
-   [x]  Breaking change (fix or feature that would cause existing functionality to not work as expected)
=> rps category_edges=None

CHANGELOG.rst, xskillscore/tests/test_deterministic.py
Closes #265
This may have been needed at one point but the tests pass without it and it may free up #221
=> rm weights.load()

setup.cfg
Keep setup.cfg inline with .pre-commit-config.yaml
We leave most of the CI to pre-commit / GHA but this helps match the settings if a developer want to run one tool locally e.g. mypy
=> sync setup.cfg with .pre-commit-config.yaml

CHANGELOG.rst, xskillscore/core/probabilistic.py, xskillscore/tests/test_probabilistic.py
allow float or int inputs
alternative solution: convert int and float inputs to xr with `xr.ones_like(forecast) * observation`
Closes #285
Replaces #340 and #341
=> Fix `brier_score` for `float` and `int` inputs

.github/workflows/cancel-duplicate-runs.yaml, .github/workflows/xskillscore_testing.yml, CHANGELOG.rst, ci/dev.yml, ci/doc.yml, ci/docs_notebooks.yml, ci/minimum-tests.yml, requirements.txt, setup.py, xskillscore/core/np_deterministic.py, xskillscore/core/np_probabilistic.py, xskillscore/core/probabilistic.py, xskillscore/core/resampling.py
sorry for https://github.com/xarray-contrib/xskillscore/commit/61d93b387dbce709e7a0cfce7eba45d8dce946b4, I played with the github VSCode integration and just pressing `.` in the browser repo and accidentally committed to `main`
Closes #359
=> remove unneccessary dependencies

CHANGELOG.rst, xskillscore/core/probabilistic.py, xskillscore/tests/test_probabilistic.py
Closes #335 
-   [x]  I have added docstrings to all new functions.
-   [x]  I have commented my code, particularly in hard-to-understand areas
-   [ ]  I have rebased onto main or develop (wherever I am merging) and dealt with any conflicts.
Hamill, T. M. (2001). Interpretation of Rank Histograms for Verifying Ensemble Forecasts. Monthly Weather Review, 129(3), 550–560. doi: 10/dkkvh3
=> `rank_histogram` tied ranks

CITATION.cff, README.rst, ci/dev.yml, ci/doc.yml, ci/docs_notebooks.yml, docs/source/index.rst, readthedocs.yml, setup.py
- use mamba for `rtd` which is faster than `conda`
- make `CITATION.cff` independent of xs version
- link to latest zenodo DOI
- add `pre-commit` badges after registering `pre-commit ci`
=> rm unnecessary package

CHANGELOG.rst, xskillscore/core/resampling.py, xskillscore/tests/test_resampling.py
=> fix `resampling_iterations_idx` on singleton forecast

.github/workflows/upstream-dev-ci.yml, ci/install-upstream-wheels.sh
reporting didnt create issue, see https://github.com/xarray-contrib/xskillscore/runs/6398733878?check_suite_focus=true
EDIT: it did https://github.com/xarray-contrib/xskillscore/issues/383
Use python 3.10 for upstream as xarray does
=> python3.10 in upstream-dev-ci.yml

CHANGELOG.rst, readthedocs.yml, xskillscore/core/probabilistic.py, xskillscore/core/utils.py, xskillscore/tests/test_probabilistic.py
=> refactor masking in `rps`

setup.py
Follows-up on #407 
- Fixes a misnamed dependency (`pytest-lazy-fixtures`)
- Adds package classifiers
- Includes LICENSE.txt in package
-   [x]  I have rebased onto main or develop (wherever I am merging) and dealt with any conflicts.
=> Fix pytest-lazy-fixtures, add classifiers and include LICENSE

.gitignore, CHANGELOG.rst, docs/source/contributors.rst, pyproject.toml, xskillscore/__init__.py
This change makes two very small changes:
1. The package now implements `setuptools-scm`. What this now means is that versioning is entirely dependent on git tags and commits, i.e. commits that are tagged will show their version according to the tag (e.g. `0.0.27`), while commits after this tag will have subsequent build history information (e.g. `0.0.27.dev66+g4e99390.d20250513`). All of this is automated thanks to a new `_version.py` file which is ignored by `git` and generated on-the-fly when building or installing the package. In other words, no more need to manage versioning within the codebase. `xskillscore.__version__` works almost exactly as before.
2. In my last PR, I forgot to modify the `accel` recipe. This now installs the relevant `numba` version and is used to compose the …
=> Use setuptools-scm for packge version handling

.github/workflows/xskillscore_testing.yml, xskillscore/core/np_deterministic.py, xskillscore/core/probabilistic.py
This fix deals with an oversight in the last release that accidentally dropped support for numpy v1. It also fixes a very small bug that can occur in numpy v2.0+, where a single value Pearson R (non-`np.ndarray`) can cause a `ValueError`.
Closes #430 
Tested locally with numpy v1.26 (should work fine with numpy v1.24) and numpy v2.0.
-   [x]  I have rebased onto main or develop (wherever I am merging) and dealt with any conflicts.
=> Fix support for numpy<2.0 and pearson_r with numpy>2.0
